# Getting started with the WriteR application {#WriteR}



The WriteR application was written to support use of R markdown and the `BrailleR` package. It is a Python script making use of wxPython to help build the graphic user interface (GUI) in such a way that it works for screen reader users. This book has been written in R markdown, and the author has made extensive use of WriteR because it offers so many convenient tools for a blind user wanting to write R markdown files.

The script is in the `BrailleR` package, but it cannot run unless the user has both Python and wxPython installed. Commands have been included in the `BrailleR` package to help Windows users obtain installation files for them. Users of other operating systems currently have to install Pandoc, Python and WxPython independently, but these tools may well already be installed.

## Getting the required software (Windows users only)

You can check if a version of Python is already installed on your computer using
```{r checkPythonExists}
Sys.which("Python")
```

The output above shows you that I have Python 2.7 installed on my computer, and that it can be found in the folder I know is the default location. You can use this command later to check your progress, but there are other ways to check that return more useful detail.

The downloaded files will be saved in your `MyBrailleR` folder. You will need to follow the instructions and answer questions that arise whenever you install new software. 

Ultimately, you will need a mainstream tool to process the markdown files you write into other formats. The WriteR application will end up using a tool called "pandoc" to do this so we need to get this installed.
If you do not have an installation of Pandoc and Python (either 2.7 or 3) then you can use some functions from the `BrailleR` package to help make the setup smoother. Remember to load the package using:
 
`library(BrailleR)`

It doesn't matter if you install Python before or after Pandoc. Let's first install Pandoc using the command:

`GetPandoc()`

There are two sets of instructions from this point onwards; you will follow only one of them. 
These are reputable installation files from the primary sites for Python and wxPython. Windows and any security software you might have should know that, but you can never tell! You will probably need to let Windows know it is OK to install the software in the default location. That pop-up might not appear as the window with focus so if things look like they're going slowly, look around for the pop-up window.


### I do not have Python 3 installed

You do not need to install Python 2.7 if you already have Python 3; the WriteR application will work with either version of Python. I preferto recommend that you install Python 2.7 here because it helps with a variety of other tools found in the `BrailleR` package.

The following  commands automatically download the installation files needed for Python 2.7, and start the installation process going. 
Issue them at the R prompt

`GetPython27()`

As the installer proceeds, there is one small matter to resolve. You need to make sure that as part of the installation, the Python folders are added to your system path. This makes it possible to run Python scripts from any folder on your computer. The next command will fail if this is not done properly. If you missed that step during the installation, look for the installer file in your `MyBrailleR` folder and run it again manually before proceding.
 
`GetWxPython27()`


Once you have completed both installations, you are ready to go. You shouldn't need to keep the  installation files, but why not keep them just in case.

### I have Python 3 installed

If you have Python 3 on your system, it is still worth installing it again so that it gets updated to the most recent release. Use

`GetPython3()`

Instructions for getting the wx module for Python 3 installed need completion. Help from a Python 3 user is clearly needed, but the latest approach using a pip command shoudl be promising. 

## Other operating systems

## Checking your system is ready

## Opening WriteR from BrailleR

Opening WriteR is as easy as typing WriteR! Well almost. You have the option of specifying a filename; if that file exists, it gets opened for you, and if it doesn't exist, then it gets created with a few lines already included at the top to help get you started. Try:

`WriteR("MyFirst.Rmd")`



## What can I do with WriteR?

The window you are in has a number of menus, a status bar at the bottom and a big space in the middle for your work. Take a quick look at those menus; some will look familiar because they are common to many Windows applications.

The file you have opened is a markdown file. It is just text which is why it is so easy to read. The file extension of `Rmd` means it is an R markdown file. There are several flavours of markdown in common use, but they are practically all the same except for some very minor differences.

A markdown file can be converted into many file formats for distribution. These include HTML, pdf, Microsoft Word, Open Office, and a number of different slide presentation formats. Let's make the HTML file now.


## Our first HTML file

Making your first HTML file is as easy as hitting the `f5` key, or using one of the options in the `Build` menu. The variety of options are the commonly used ones in RStudio.

This will use the suite of packages, primarily including the `knitr` and `rmarkdown` packages.
process 
Navigate to the current working directory using your file browser. To find out where that is, type `getwd()` back in the R window. You should see the file `MyFirst.Rmd` and once you have built it, the associated HTML file.

Open the HTML file and see how the markdown has been rendered. You may need to switch back and forth between the WriteR window and your browser to compare the plain text and the beautiful HTML.

Changes in your R markdown file are not automatically converted into the HTML file. You must re-build the HTML, and refresh your browser to see the impact of any changes you make.

## BrailleR commands used in this chapter

We needed to use either `GetPython27()` and `GetWxPython27()` or `GetPython3()` to install the necessary software to allow us to run a Python script like WriteR. 
We then opened a new file using `WriteR()`.

