# The Work Ahead {#LookingAhead}

The `BrailleR` Project is likely to evolve over time. The work on the project will be dependent on interest being shown by blind users of R, and perhaps some willingness being shown by people who could make the work so much easier.

Developments that meet specific requests from blind users are being addressed. For example, the request from one user to have the `BrailleR` package loaded in every session led to creation of a `MakeRprofile()` function; this function simplifies the experience for the user (a novice) for creation of the `.Rprofile` file in the current working directory. This is easier to explain to a novice than the process of altering the `.Rprofile` or `.Rprofile.site` files.

A request for assistance getting braille labels onto graphs has brought forward the plans to address this issue within the `BrailleR` package. The experimental `BRLThis()` function has been included in the package, as well as a similar `SVGThis()` function to optimise the settings for creation of a version using a braille font and a structured SVG file for a graph. The `BRLThis()` function creates a pdf document that has been successfully embossed on two different models of embosser, while SVG files generated by the `SVGThis()` function have only the bare minimum of useful content at this stage.
 
It may prove necessary for the `BRLThis()` function to be converted to a method like the `SVGThis()` functions so that the best results can be created for different graph types. At present, the `SVGThis()` is reliant on the existence of the `hist()` and `boxplot()` commands within the `BrailleR` package that are wrappers to the `graphics` package functions of the same name.
It is my hope that I can encourage the R development core team to create more classes. The additions are almost trivial from their perspective, but the workload for me as a programmer will reduce markedly if I can write simpler code to interpret the graphs. Knowing what type of graph has been created by an object rather than writing code that makes a reasonable attempt at guessing what type of graph was created is a key example. To this end, it will prove easier to work with the graphs created by the `xyplot()` function from the `lattice` package than the standard `plot()` command.

I will also need feedback from students and users of R, and perhaps their lecturers, tutors,  and teachers, to see which ideas are working well for blind users. At present, the attempts being made are based on my own experiences and desires; I wanted functions to convert an R script to an R markdown file and a similr function to convert the history of commands to an Rmd file. The `R2Rmd()` and `History2Rmd()` functions were duly created;  they have proven very useful in my work. I can only hoep others find them as useful. I am, therefore, seeking opportunities to share my work with blind users all over the world via a specially created email list for those people interested in how blind users can work with R{}. I believe that 
 adding perspectives is a crucial pathway for the project's development and all feedback is extremely welcome. 


A key contribution is possible in the area of choosing appropriate default text for the `BrailleR` output. The text representation needs to be more efficient than using R in its vanilla form. To this end, I have put some time into thinking about which text will be most suitable for an audience that will often listen to the output using synthetic speech, perhaps in the user's second language, as well as the braille readers who may or may not be able to use contracted English braille. At first, I had thought this task would be made easier by reviewing resources created by transcribers who record books for the blind, but my investigations show that the descriptions used in spoken words do not always equate to efficient braille or synthetic speech and often provide more interpretation than I believe is appropriate in educational settings.

Collaboration from others in any role will feed my own enthusiasm for the project, especially those whose skills and knowledge complement my own. 
The work of willing and helpful contributors  has been gratefully received. 
In some instances, other researchers in the R community have inadvertently contributed to `BrailleR` because I have been able to adapt their work to meet the needs of blind users.
