attach(airquality)
SummaryResponse <- summary(na.omit(Ozone))
SummaryPredictor <- summary(na.omit(Wind))
SummaryTable <- cbind(Ozone=SummaryResponse,Wind=SummaryPredictor)
row.names(SummaryTable) <- c("Minimum","Lower Quartile", "Median","Mean","Upper Quartile","Maximum")
Sds <- c(sd(Ozone, na.rm=T),sd(Wind, na.rm=T))
Nas <- c(sum(is.na(Ozone)), sum(is.na(Wind)))
SummaryTable <- rbind(SummaryTable,"Standard Deviation"=Sds,"Missing Values"=Nas)
detach(airquality)
# Remove the missing values
completeCases <- complete.cases(Data[ResponseName])*complete.cases(Data[PredictorName])
assign(DataName, Data[completeCases==1,])

plot(Ozone~Wind, data=airquality, ylab=Ozone, xlab=Wind)
attach(airquality)
WhereXY(Ozone,Wind)
detach(airquality)
Ozone.Wind.lm <- lm(Ozone~Wind, data=airquality)
VI( Ozone.Wind.lm )
VI(summary(Ozone.Wind.lm))
summary(Ozone.Wind.lm)
plot(Ozone~Wind, data=airquality, ylab=Ozone, xlab=Wind)
abline(Ozone.Wind.lm)
par(mfrow=c(2,2))
plot(Ozone.Wind.lm)
anova(Ozone.Wind.lm)
